apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-07-02T02:29:26Z"
  labels:
    run: busybox
spec:
  containers:
  - args:
    - sh
    image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-p6jc5
      readOnly: true
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-p6jc5
    secret:
      defaultMode: 420
      secretName: default-token-p6jc5
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-07-02T02:29:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-07-02T02:29:28Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-07-02T02:29:28Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-07-02T02:29:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://315a5a63fe6a21bf219846c2a5d6e151ce920dc2e1cd4911d95f2afa27220d77
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:9ddee63a712cea977267342e8750ecbc60d3aab25f04ceacfa795e6fce341793
    lastState: {}
    name: busybox
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-07-02T02:29:28Z"
  hostIP: 192.168.4.33
  phase: Running
  podIP: 10.42.1.23
  podIPs:
  - ip: 10.42.1.23
  qosClass: BestEffort
  startTime: "2020-07-02T02:29:26Z"
