apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole
    metallb.universe.tf/address-pool: private
  labels:
    app: pihole
  name: pihole-tcp
  namespace: pihole
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.4.50
  ports:
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  - name: pihole-https
    port: 443
    protocol: TCP
    targetPort: pihole-https
  - name: dns
    port: 53
    protocol: TCP
    targetPort: dns
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: private
    metallb.universe.tf/allow-shared-ip: pihole
  labels:
    app: pihole
  name: pihole-udp
  namespace: pihole
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.4.50
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
  - name: client-udp
    port: 67
    protocol: UDP
    targetPort: client-udp
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer

