apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boinc-arm
  name: boinc-arm
  namespace: boinc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boinc-arm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: boinc-arm
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - boinc-arm
            topologyKey: "kubernetes.io/hostname"

      containers:
      - name: boinc-worker
        image: boinc/client:arm32v7
        env:
        - name: TZ
          value: "America/New_York"
        - name: BOINC_GUI_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: boinc-secret
              key: BOINC_GUI_RPC_PASSWORD
        - name: BOINC_CMD_LINE_OPTIONS
          value: "--allow_remote_gui_rpc"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 31416
            name: manager
            protocol: TCP
      nodeSelector:
        kubernetes.io/arch: arm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boinc-x86
  name: boinc-x86
  namespace: boinc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boinc-x86
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: boinc-x86
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - boinc-x86
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: boinc-worker
        image: boinc/client
        env:
        - name: TZ
          value: "America/New_York"
        - name: BOINC_GUI_RPC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: boinc-secret
              key: BOINC_GUI_RPC_PASSWORD
        - name: BOINC_CMD_LINE_OPTIONS
          value: "--allow_remote_gui_rpc"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 31416
            name: manager
            protocol: TCP
      nodeSelector:
        kubernetes.io/arch: amd64


