---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: small-storage-arm
  namespace: boinc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: small-storage-x86
  namespace: boinc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---


