apiVersion: v1
kind: Service
metadata:
  name: boinc-arm
  namespace: boinc
  annotations:
    metallb.universe.tf/address-pool: private
spec:
  selector:
    app: boinc-arm
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
    - port: 31416
      name: manager
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: boinc-x86
  namespace: boinc
  annotations:
    metallb.universe.tf/address-pool: private
spec:
  selector:
    app: boinc-x86
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
    - port: 31416
      name: manager
      protocol: TCP
  type: LoadBalancer

