apiVersion: apps/v1
kind: Deployment
metadata:
  name: trails
  namespace: trails
  labels:
    app: trails
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trails
  template:
    metadata:
      name: trails
      labels:
        app: trails
    spec:
      containers:
        - name: trails
          image: nashluffy/trailsapi:latest
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
