apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: website
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      name: flask
      labels:
        app: flask
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm
      tolerations:
      - key: kubernetes.io/arch
        operator: "Equal"
        value: arm
        effect: "NoSchedule"
      containers:
        - name: flask
          image: nashluffy/flask:latest
          ports:
          - name: https
            containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"
