apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: website
  annotations: 
    traefik.frontend.entryPoints: / 
spec:
  tls:
   - secretName: traefik-ui-tls-cert
  rules:
  - host: nashluffman.com
    http:
      paths:
      - path: /
        backend:
          serviceName: flask
          servicePort: 80
