apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask
  name: flask-service
  namespace: website
spec:
  ports:
    - protocol: TCP
      name: flask-http-tcp
      port: 80
      targetPort: 8080
  type: NodePort
  selector:
    app: flask
