#!/bin/bash
#This script will place the token in your clipboard and open the kubernetes dashboard
token=$(kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}') | grep -E 'token:' | awk '{print $2}')
echo $token | xclip -selection clipboard
sleep 5 && firefox -new-tab 'http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login' &
kubectl proxy
