apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: nashluffman@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "nashluffman.com"
      dns01:
        route53:
          region: us-east1
          accessKeyID: AKIASWGYKCGC2QE2QENB 
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key
